# Generated by Django 5.1.1 on 2026-05-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='benefits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly')], default='daily', max_length=10),
        ),
    ]
