# Generated by Django 5.1.1 on 2026-05-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='employee_qrcodes/'),
        ),
    ]
