# Generated by Django 5.1.1 on 2026-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_college_employee_college_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='barangay_clearance_file',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/barangay/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='barangay_clearance_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license_file',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/drivers_license/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='drivers_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nbi_clearance_file',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/nbi/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nbi_clearance_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='philhealth_file',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/philhealth/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='philhealth_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss_file',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/sss/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin_file',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/tin/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
