# Generated by Django 6.0 on 2026-05-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_photo_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESIGNED', 'Resigned'), ('MIA', 'MIA')], default='ACTIVE', max_length=20),
        ),
    ]
