# Generated by Django 6.0 on 2026-05-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESIGNED', 'Resigned'), ('MIA', 'MIA'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
    ]
