# Generated by Django 6.0 on 2026-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_employment_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
