# Generated by Django 6.0 on 2026-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employee_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pagibig_file',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/pagibig/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pagibig_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
