# Generated by Django 6.0 on 2026-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_options_payroll_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='delivery_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transportation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='is_deducted',
            field=models.BooleanField(default=False, help_text='Automatically marked once included in payroll.'),
        ),
    ]
