# Generated by Django 6.0 on 2026-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_delivery_allowance_payroll_overtime_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual allowance for this payroll period.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='is_deducted',
            field=models.BooleanField(default=False, help_text='For future payroll correction use only.'),
        ),
    ]
