# Generated by Django 6.0 on 2026-05-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_remarks_alter_payroll_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='total_late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_undertime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Manual allowance for this payroll period.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='cash_advance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
