# Generated by Django 6.0 on 2026-07-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payroll_total_late_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='absent_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
