# Generated by Django 5.2.6 on 2026-04-25 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_id'),
        ('employees', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('adjustment_type', models.CharField(choices=[('benefit', 'Benefit'), ('cash_advance', 'Cash Advance'), ('charge', 'Charge'), ('rent', 'Rent')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='employees.employee')),
            ],
        ),
    ]
