# Generated by Django 6.0 on 2026-05-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_payrolladjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='transportation_fee_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='PayrollAdjustment',
        ),
    ]
