# Generated by Django 6.0 on 2026-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_transportation_fee_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
