# Generated by Django 6.0 on 2026-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_location',
            field=models.CharField(blank=True, help_text='Example: Digos, Kidapawan, Tagum', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_type',
            field=models.CharField(choices=[('office', 'Office'), ('deliver', 'Deliver'), ('booking', 'Booking')], default='office', max_length=20),
        ),
    ]
