# Generated by Django 6.0 on 2026-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_work_location_attendance_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('rest_day', 'Rest Day'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
    ]
