# Generated by Django 6.0 on 2026-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_applicable',
            field=models.BooleanField(default=False, help_text='Check this if overtime should be counted.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
