# Generated by Django 6.0 on 2026-05-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendance_overtime_applicable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overtime_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
