# Generated by Django 6.0 on 2026-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendance_overtime_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='delivery_allowance_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
